#define	C_LOCATEDBF		"Va rog sa precizati tabelul:"
#define	C_OUTPUT		"Numele tabelului de intrare trebuie sa fie diferit cu al celui de iesire."
#define	C_NEED3FLDS		"Tabelul de intrare trebuie sa contina cel putin trei campuri"
#define	C_EMPTYDBF		"Nu se poate face pivot asupra dintr-un tabel gol"
#define	C_BADPAGEFLD	"Campul pentru pagina nu poate fi memo, general or picture  field."
#define	C_BADROWFLD		"Campul pentru rand nu poate fi memo, general or picture  field."
#define	C_BADCOLFLD		"Campul pentru coloana nu poate fi memo, general or picture field."
#define	C_BADCELLFLD	"Campul pentru celula nu poate fi memo, general or picture field."
#define	C_NOCOLS		"Nici o coloana."
#define	C_XSVALUES		"Prea multe valori unice pentru campul coloane. Maximum este 254."
#define	C_UNKNOWNFLD	"Tip de data necunoscut."
