#define	C_LOCATEDBF		"Выберите входную таблицу:"
#define	C_OUTPUT		"Входные и выходные таблицы должны быть различны."
#define	C_NEED3FLDS		"Во входной базе данных кросс-таблицы требуется как минимум три поля."
#define	C_EMPTYDBF		"Входная база данных пуста."
#define	C_BADPAGEFLD	"Поле страниц кросс-таблицы во входных данных не может иметь тип Memo, General или Picture."
#define	C_BADROWFLD		"Поле строк кросс-таблицы во входных данных не может иметь тип Memo, General или Picture."
#define	C_BADCOLFLD		"Поле столбцов кросс-таблицы во входных данных не может иметь тип Memo, General или Picture."
#define	C_BADCELLFLD	"Поле данных кросс-таблицы во входных данных не может иметь тип Memo, General или Picture."
#define	C_NOCOLS		"Ни одно значение столбцов не найдено."
#define	C_XSVALUES		"Число уникальных значений для поля столбцов не может превышать 254."
#define	C_UNKNOWNFLD	"Неизвестный тип поля."
