#define	C_LOCATEDBF		"Please locate the input database:"
#define	C_OUTPUT		"The input and output databases must be different."
#define	C_NEED3FLDS		"Crosstab input databases require at least three fields"
#define	C_EMPTYDBF		"Cannot prepare crosstab on empty database"
#define	C_BADPAGEFLD	"The crosstab page field in the input database cannot be a memo, general or picture  field."
#define	C_BADROWFLD		"The crosstab row field in the input database cannot be a memo, general or picture  field."
#define	C_BADCOLFLD		"The crosstab column field in the input database cannot be a memo, general or picture field."
#define	C_BADCELLFLD	"The crosstab cell field in the input database cannot be a memo, general or picture field."
#define	C_NOCOLS		"No columns found."
#define	C_XSVALUES		"There are too many unique values for column field. The maximum is 254."
#define	C_UNKNOWNFLD	"Unknown field type."
